### ISSUE TITLE
Неочікуваний результат при пошуку через DuckDuckGo

### ISSUE THREAD

**Issue by InfoZebra** [brown-uk/r2u.org.ua#3]
Коли я шукаю переклад слова з російської на українську, наприклад [!r2u обнищание](https://duckduckgo.com/?t=lm&q=%21r2u+%D0%BE%D0%B1%D0%BD%D0%B8%D1%89%D0%B0%D0%BD%D0%B8%D0%B5), то відкриваються не російсько-українські словники, а англійсько-українські, хоча доменне ім'я залишається r2u.org.ua. 
![image](https://user-images.githubusercontent.com/79378855/112986041-aaea2f80-9169-11eb-97f9-ba5e789262b7.png)
https://duckduckgo.com/bang?q=українські

**Comment by InfoZebra** [comment]
Цікаво, що 
https://www.r2u.org.ua/s?w=%D0%BE%D0%B1%D0%BD%D0%B8%D1%89%D0%B0%D0%BD%D0%B8%D0%B5&scope=all&dicts=all&highlight=on
та 
https://r2u.org.ua/s?w=%D0%BE%D0%B1%D0%BD%D0%B8%D1%89%D0%B0%D0%BD%D0%B8%D0%B5&scope=all&dicts=all&highlight=on (без www),
показують різні словники: в першому випадку англійсько-українські, в другому - російсько-українські. Я надіслав в DuckDuckGo запит на виправлення (щоб прибрали ці www), тож планую закрити це питання. Але і на вашому сервісі це має бути виправлено, я вважаю.

**Comment by arysin** [comment]
Дякую, я додав permanent redirect з www.r2u.org.ua
