### ISSUE TITLE
Беззмістовний текст ("Кобів": "sloppy small")

### ISSUE THREAD

**Issue by bobbib** [brown-uk/r2u.org.ua#4]
Випадково знайшов у одному зі словників ("14. Кобів. Словник судинних рослин") [25 статей](https://r2u.org.ua/s?w=sloppy&scope=all&dicts=14&highlight=on), що закінчуються беззмістовним англ. текстом ("sloppy small").

**Comment by arysin** [comment]
Дякую, пролізло з latex, виправив
