### ISSUE TITLE
Одрук? ("Кобів")

### ISSUE THREAD

**Issue by bobbib** [brown-uk/r2u.org.ua#5]
[Знайшов](https://r2u.org.ua/s?w=colomikta&scope=all&dicts=14&highlight=on) у ботанічному словнику ("14. Кобів. Словник судинних рослин") гасло "Actinidia **c**olomikta".

За доступними джерелами &mdash; правильно слід писати "**k**olomikta":
* https://uk.wikipedia.org/wiki/%D0%90%D0%BA%D1%82%D0%B8%D0%BD%D1%96%D0%B4%D1%96%D1%8F_%D0%BA%D0%BE%D0%BB%D0%BE%D0%BC%D1%96%D0%BA%D1%82%D0%B0
* https://en.wikipedia.org/wiki/Actinidia_kolomikta
* https://www.gbif.org/species/7270682

(Якщо так було написано в паперовій версії словника &mdash; можливо, хай так і залишається?)

**Comment by vstarko** [comment]
Треба виправити на kolomikta.

**Comment by arysin** [comment]
Дякую, виправлю.

**Comment by bobbib** [comment]
> (Якщо так було написано в паперовій версії словника — можливо, хай так і залишається?)

В друкованій версії ([с. 38](https://archive.org/details/sl0vn2004/page/38/mode/1up)) таки "**c**olomikta"...

**Comment by arysin** [comment]
Виправлено
